# Dockerfile.jvm
FROM eclipse-temurin:21-jre

WORKDIR /app

# Copy all Quarkus build output
COPY build/quarkus-app/ ./

# (Optional) check file exists before running
RUN test -f quarkus-run.jar || (echo "❌ quarkus-run.jar not found in /app" && ls -R /app && exit 1)

EXPOSE 8080
CMD ["java", "-jar", "quarkus-run.jar"]
