services:
  healthatlas-auth:
    build:
      context: .
      dockerfile: Dockerfile.jvm # Switch to Dockerfile.native later for native
    image: healthatlas-auth:latest
    container_name: cerberus
    ports:
      - "8081:8080"
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:postgresql://cerberus-db:5432/cerberus
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_PROFILE: dev
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/q/health" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
  postgres:
    image: postgres:15
    container_name: cerberus-db
    environment:
      POSTGRES_DB: cerberus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s
    volumes:
      - pgdata-cerberus:/var/lib/postgresql/data
volumes:
  pgdata-cerberus: