quarkus:
  profile: dev
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5434/cerberus
  flyway:
    migrate-at-start: true
    locations: db/migration
