# Common defaults (used when no profile override)
greeting:
  message: "hello"

quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: ${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5434/cerberus}
  http:
    port: 8080
  flyway:
    migrate-at-start: true
    locations: db/migration
  log:
    category:
      org.flywaydb:
        level: DEBUG